# services:
#  #air flow
#   airflow:
#     image: apache/airflow:2.6.0-python3.9
#     command: airflow
#     entrypoint: ['/opt/airflow/script/entrypoint.sh']
#     depends_on:
#       - postgres
#     environment:
#       - LOAD_EX=n
#       - EXECUTOR=Sequential
#       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
#       - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
#     logging:
#       options:
#         max-size: 10m
#         max-file: "3"
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
#       - ./requirements.txt:/opt/airflow/requirements.txt
#     ports:
#       - "8080:8080"
#     healthcheck:
#       test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
#       interval: 30s
#       timeout: 30s
#       retries: 3
#     networks:
#       - confluent

#   scheduler:
#     image: apache/airflow:2.6.0-python3.9
#     depends_on:
#       airflow:
#         condition: service_healthy
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
#       - ./requirements.txt:/opt/airflow/requirements.txt
#     environment:
#       - LOAD_EX=n
#       - EXECUTOR=Sequential
#       - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
#       - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
#     command: bash -c "pip install -r ./requirements.txt && airflow db upgrade && airflow scheduler"
# networks:
#       - confluent