version: '1'
services:
  micro:
    container_name: snowplow-micro
    image: snowplow/snowplow-micro:2.0.0
    volumes:
      - ./config/iglu-conf:/config
      - ./config/collector-conf:/config
      - ./micro/iglu-client-embedded:/config/iglu-client-embedded/
      - ./micro/my-enrichments:/config/enrichments
    ports:
      - "9090:9090"
    command: "--iglu /config/iglu.json"
  # stream-kafka-collector:
  #   container_name: kafka-collector
  #   image: snowplow/scala-stream-collector-kafka:3.1.0
  #   volumes:
  #     - ./config/collector:/snowplow/config
  #   ports:
  #     - "8080:8080"
  #   command: "--config /snowplow/config/kafka.conf"
